### ISSUE TITLE
(ab.sprite.Player) Returns error

### ISSUE THREAD

**Issue by desvasicek** [desvasicek/Abinde#5]
code:

```python
player = ab.sprite.Player(ab.LoadImage("dino-assets/sheets/DinoSprites - tard.png"), "pygame")
``` 

returns error: 

```yaml
Traceback (most recent call last):
  File "/home/therealpenguin/ab/tests/game_test.py", line 5, in <module>
    player = ab.sprite.Player(ab.LoadImage("dino-assets/sheets/DinoSprites - tard.png"), "pygame")
  File "/home/therealpenguin/.local/lib/python3.9/site-packages/Abinde.py", line 168, in __init__
    self.rect.center = self.pos
TypeError: invalid rect assignment
```

**Comment by desvasicek** [comment]
I don't know how I fixed it?
